services:
  - type: web
    name: event-management-planner
    plan: free
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan key:generate
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
      php artisan migrate --force
      php artisan db:seed --class=DatabaseCleanupSeeder
    startCommand: php artisan serve --host 0.0.0.0 --port $PORT
           envVars:
             - key: APP_NAME
               value: TheFinestGroup Event Management
             - key: APP_ENV
               value: production
             - key: APP_DEBUG
               value: false
             - key: APP_URL
               value: https://sss.thefinestgroup.co.uk
             - key: APP_TIMEZONE
               value: GMT
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: dpg-d36pkd3uibrs73aihe5g-a.oregon-postgres.render.com
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: event_management_2xw5
      - key: DB_USERNAME
        value: event_user
      - key: DB_PASSWORD
        value: ThxhBQaeDfhCRybZAHn1vauvuRccvIUo
      - key: CACHE_DRIVER
        value: database
      - key: SESSION_DRIVER
        value: database
      - key: SESSION_LIFETIME
        value: 120
      - key: SESSION_ENCRYPT
        value: false
      - key: SESSION_PATH
        value: /
      - key: SESSION_DOMAIN
        value: null
      - key: SESSION_SECURE_COOKIE
        value: true
      - key: QUEUE_CONNECTION
        value: database